"""Embedded bootstrap data for ``case_phase`` / ``ai_interaction`` DB seed and pytest snapshot mode.

Production runtime SSOT is PostgreSQL. Regenerated by ``scripts/generate_interaction_ai07_ai34.py`` when refreshing assessment_07…assessment_34 templates.
"""

from __future__ import annotations

import json
from typing import Any

CASE_PHASE_ASSESSMENT_MANIFEST: dict[str, Any] = {
    "version": "1",
    "description": "Bootstrap phase → AssessmentCode mapping for DB seed; SSOT after seed is PostgreSQL.",
    "phases": {
        "ONBOARDING": [
            "onboarding_completeness",
            "client_profile_context",
            "client_explain_onboarding",
            "document_request_draft",
            "special_situation_detect"
        ],
        "DISCOVERY": [
            "client_summary_structure",
            "planning_readiness_gap",
            "assessment_07",
            "assessment_08"
        ],
        "PLANNING": [
            "assessment_09",
            "assessment_10",
            "assessment_11",
            "assessment_12",
            "assessment_13",
            "assessment_14",
            "assessment_15"
        ],
        "COLLABORATION": [
            "assessment_16",
            "assessment_17",
            "assessment_18",
            "assessment_19",
            "assessment_20",
            "assessment_30",
            "assessment_31"
        ],
        "EXECUTION": [
            "assessment_21",
            "assessment_22",
            "assessment_23",
            "assessment_24",
            "assessment_25"
        ],
        "MONITORING": [
            "assessment_26",
            "assessment_27",
            "assessment_28",
            "assessment_29",
            "assessment_32",
            "assessment_33",
            "assessment_34"
        ]
    }
}

_INTERACTION_CATALOG_SEED_RAW = r"""
{
  "onboarding_completeness": {
    "loop_input": {
      "loop_id": "completeness_lp_000",
      "case_id": "CASE-ONB-001",
      "client_id": "CL-1001",
      "request_type": "ASSESS_ONBOARDING_COMPLETENESS",
      "goal": "Assess whether onboarding information is complete and identify missing information or documents",
      "current_context": {
        "known_context": {
          "client_name": "Linh Nguyen",
          "age": 42,
          "marital_status": "Married",
          "channel": "Internal FE"
        }
      },
      "expected_llm_response_format": {
        "type": "yaml",
        "required_fields": [
          "loop_id",
          "loop_status",
          "reasoning_summary",
          "actions",
          "expected_next_input_format",
          "result_evaluation"
        ],
        "field_definitions": {
          "loop_id": {
            "type": "string"
          },
          "loop_status": {
            "type": "string",
            "allowed_values": [
              "CONTINUE",
              "WAIT_USER",
              "WAIT_APPROVAL",
              "ESCALATE",
              "FINISH",
              "FAIL"
            ]
          },
          "reasoning_summary": {
            "type": "string"
          },
          "actions": {
            "type": "array",
            "item_schema": {
              "action_id": "string",
              "actor": {
                "type": "object",
                "fields": {
                  "actor_type": "SYSTEM | HUMAN | LLM",
                  "actor_name": "string"
                }
              },
              "action_type": "string",
              "purpose": "string",
              "execution": {
                "type": "object",
                "fields": {
                  "method": "SQL | INTERNAL_API | WORKFLOW_TASK | ARTIFACT_GENERATION",
                  "details": "object"
                }
              },
              "expected_action_output": {
                "type": "object",
                "fields": {
                  "name": "string",
                  "schema": "object"
                }
              }
            }
          },
          "expected_next_input_format": {
            "type": "object",
            "fields": {
              "required_artifacts": [
                "string"
              ],
              "schema": {
                "type": "object"
              }
            }
          },
          "result_evaluation": {
            "type": "object",
            "fields": {
              "is_goal_achieved": "boolean",
              "missing_items": [
                "string"
              ],
              "completion_score": "number"
            }
          }
        }
      },
      "execution_constraints": {
        "allowed_action_types": [
          "QUERY_SSOT",
          "QUERY_DOCUMENT_STORE",
          "RUN_RULE_CHECK",
          "REQUEST_USER_INPUT",
          "REQUEST_DOCUMENT",
          "REQUEST_SPECIALIST_REVIEW",
          "UPDATE_CASE_STATE"
        ]
      }
    },
    "system_prompt": "# you act a LLM reasoning core for the wealth management system. I will provide a input, you will provide a response.\nAlways reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output.\n{{loop_input}}"
  },
  "client_explain_onboarding": {
    "loop_input": {
      "interaction_id": "client_explain_onboarding",
      "journey_phase": "Onboarding / Client Setup",
      "requester": "Client",
      "request_intent": "Explain onboarding questions to client",
      "business_trigger_context": "Client using mobile onboarding screens",
      "input": "Current screen context; field / questionnaire item; client role; onboarding requirements",
      "output": "Plain-language explanation; examples; next-action guidance",
      "expectation_to_ai": "Explain clearly in non-technical language; reduce abandonment; avoid legal over-promising; do not alter required data-collection rules",
      "human_in_the_loop": "No, unless escalated",
      "ai_type": "Explanation / Client assist",
      "priority": "MVP",
      "notes": "Client-facing tone required"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent case facts. Use plain language suitable for a client on mobile. Follow the output contract above. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "document_request_draft": {
    "loop_input": {
      "interaction_id": "document_request_draft",
      "journey_phase": "Onboarding / Client Setup",
      "requester": "RM / Operations / Compliance",
      "request_intent": "Generate request for additional documents",
      "business_trigger_context": "Missing or insufficient onboarding/case documents",
      "input": "Current client profile; uploaded documents; detected special situation; missing-document rules",
      "output": "Specific list of required documents; explanation of why each document is needed; client-facing message draft",
      "expectation_to_ai": "Request specific documents, not generic requests; detect special cases (trust, estate, guardianship, inheritance, business-owner, cross-border) and tailor document request accordingly",
      "human_in_the_loop": "RM / Operations review before sending",
      "ai_type": "Validation / Drafting / Next-best-action",
      "priority": "MVP",
      "notes": "High value for onboarding efficiency"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent case facts. Tailor document requests to special situations when indicated by Variables. Follow the output contract above. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "special_situation_detect": {
    "loop_input": {
      "interaction_id": "special_situation_detect",
      "journey_phase": "Onboarding / Client Setup",
      "requester": "System / RM / Compliance",
      "request_intent": "Detect special onboarding situations",
      "business_trigger_context": "After profile + household + suitability + discovery data capture",
      "input": "Household structure; source-of-wealth indicators; legal relationships; declared goals; client notes",
      "output": "Special situation flags; suggested specialist involvement; follow-up questions",
      "expectation_to_ai": "Detect family trust/trustee/guardian involvement; inheritance/succession complexity; business-owner wealth; cross-border tax/residency issues; minors/guardianship; unusual liquidity mismatch",
      "human_in_the_loop": "RM / Compliance",
      "ai_type": "Pattern detection / Risk flagging",
      "priority": "MVP",
      "notes": "Should trigger downstream workflows"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent case facts. Output flags and follow-up questions suitable for RM/Compliance review. Follow the output contract above. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "client_summary_structure": {
    "loop_input": {
      "interaction_id": "client_summary_structure",
      "journey_phase": "Discovery / Data Collection",
      "requester": "RM / WM",
      "request_intent": "Build structured client summary from onboarding + discovery",
      "business_trigger_context": "Discovery completed or RM preparing for planning",
      "input": "Profile; goals; assets/liabilities; cash flow; risk profile; household data; notes",
      "output": "Client summary; key facts; risks / constraints; unresolved questions",
      "expectation_to_ai": "Convert raw information into concise, structured planning summary; identify major planning drivers; identify data gaps; highlight contradictions",
      "human_in_the_loop": "RM / WM review",
      "ai_type": "Summarization / Structuring",
      "priority": "MVP",
      "notes": "Used as planning input",
      "tools": ["client_profile_sql_tool", "discovery_dataset_sql_tool"],
      "loader_sections": ["identity", "household", "documents", "assets", "goals"]
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent case facts. Produce a concise structured summary; call out gaps and contradictions. Follow the output contract above. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "planning_readiness_gap": {
    "loop_input": {
      "interaction_id": "planning_readiness_gap",
      "journey_phase": "Discovery / Data Collection",
      "requester": "Wealth Manager",
      "request_intent": "Identify what else is needed before planning",
      "business_trigger_context": "Planning cannot start confidently",
      "input": "Current wealth data; goals; assumptions; constraints",
      "output": "Missing data list; follow-up questions; optional document requests",
      "expectation_to_ai": "Determine if data is sufficient for a credible plan; request targeted information such as future cash needs, external liabilities, concentrated holdings, trust/inheritance arrangements, tax residency/legal conditions",
      "human_in_the_loop": "WM / RM",
      "ai_type": "Validation / Gap analysis",
      "priority": "MVP",
      "notes": "Critical planning-readiness interaction",
      "tools": ["client_profile_sql_tool", "discovery_dataset_sql_tool"],
      "loader_sections": ["identity", "household", "documents", "assets", "goals"]
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent case facts. Focus on planning-readiness gaps and targeted follow-up questions. Follow the output contract above. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_07": {
    "loop_input": {
      "interaction_id": "assessment_07",
      "journey_phase": "Discovery / Data Collection",
      "requester": "System / WM / IM",
      "request_intent": "Normalize and interpret client assets / liabilities / holdings",
      "business_trigger_context": "Client entered or linked financial data",
      "input": "Account data; manually entered holdings; asset/liability categories; cash-flow data",
      "output": "Normalized financial structure; categorized assets/liabilities; suspicious / unclear items",
      "expectation_to_ai": "Classify financial data correctly; identify ambiguity or inconsistency; detect unusual assets requiring specialist handling",
      "human_in_the_loop": "WM / RM / Operations if necessary",
      "ai_type": "Normalization / Classification",
      "priority": "MVP",
      "notes": "AI should not silently guess unclear assets",
      "tools": "client_profile_sql_tool",
      "loader_sections": ["identity", "assets"]
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_08": {
    "loop_input": {
      "interaction_id": "assessment_08",
      "journey_phase": "Discovery / Data Collection",
      "requester": "Wealth Manager",
      "request_intent": "Detect conflicting goals or constraints",
      "business_trigger_context": "During discovery or plan drafting",
      "input": "Goals; target dates; target amounts; risk tolerance; liquidity requirements; asset base",
      "output": "Identified goal conflicts; trade-off summary; suggested clarification questions",
      "expectation_to_ai": "Detect infeasible or conflicting goals; explain conflict in practical terms; suggest which assumptions require confirmation",
      "human_in_the_loop": "WM",
      "ai_type": "Reasoning / Conflict detection",
      "priority": "MVP",
      "notes": "Supports scenario setup",
      "tools": "client_profile_sql_tool",
      "loader_sections": ["identity", "assets", "goals"]
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_09": {
    "loop_input": {
      "interaction_id": "assessment_09",
      "journey_phase": "Plan Creation / Wealth Plan Drafting",
      "requester": "Wealth Manager",
      "request_intent": "Build draft wealth plan",
      "business_trigger_context": "Sufficient discovery data available",
      "input": "Client data; goals; assets/liabilities; cash flow; constraints; risk profile; related-party / special-case data",
      "output": "Draft wealth plan; request for more information if needed; assumptions used; key planning rationale",
      "expectation_to_ai": "Validate whether information is sufficient; request more information if not enough; produce comprehensive and customized plan draft; detect special situations; ask for specific documents/facts depending on the client situation; avoid generic template planning",
      "human_in_the_loop": "WM must review",
      "ai_type": "Reasoning / Drafting / Gap analysis",
      "priority": "MVP",
      "notes": "Key planning interaction for developers"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_10": {
    "loop_input": {
      "interaction_id": "assessment_10",
      "journey_phase": "Plan Creation / Wealth Plan Drafting",
      "requester": "Wealth Manager",
      "request_intent": "Run scenario analysis and compare options",
      "business_trigger_context": "Draft plan available, options needed",
      "input": "Draft plan; assumptions; scenario parameters; client goals and constraints",
      "output": "Scenario comparison; trade-off summary; recommended option",
      "expectation_to_ai": "Compare scenarios in goal-oriented form; explain advantages/disadvantages; identify scenarios requiring client confirmation",
      "human_in_the_loop": "WM",
      "ai_type": "Scenario analysis / Comparison",
      "priority": "MVP",
      "notes": "Output should be structured for screen display"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_11": {
    "loop_input": {
      "interaction_id": "assessment_11",
      "journey_phase": "Plan Creation / Wealth Plan Drafting",
      "requester": "Wealth Manager / System",
      "request_intent": "Detect need for specialist involvement during planning",
      "business_trigger_context": "During plan drafting",
      "input": "Draft plan; client structure; assets; goals; cross-border / trust / inheritance data",
      "output": "Specialist referral recommendation; reason for referral; suggested tasks/questions",
      "expectation_to_ai": "Identify when general planning is not sufficient; trigger Legal / Tax / Compliance appropriately; explain the reason clearly",
      "human_in_the_loop": "WM / RM",
      "ai_type": "Routing / Risk flagging",
      "priority": "MVP",
      "notes": "Feeds routing engine"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_12": {
    "loop_input": {
      "interaction_id": "assessment_12",
      "journey_phase": "Plan Creation / Wealth Plan Drafting",
      "requester": "Wealth Manager / RM",
      "request_intent": "Draft plan rationale and client-facing explanation",
      "business_trigger_context": "Draft plan ready for internal review or client delivery",
      "input": "Plan draft; scenario selection; rationale; client profile / communication style",
      "output": "Internal rationale; client-facing explanation; meeting talking points",
      "expectation_to_ai": "Produce both professional internal explanation and plain-language client explanation; preserve consistency with approved assumptions",
      "human_in_the_loop": "WM / RM",
      "ai_type": "Drafting / Explanation",
      "priority": "MVP",
      "notes": "Must not introduce new facts not in SSOT"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_13": {
    "loop_input": {
      "interaction_id": "assessment_13",
      "journey_phase": "Portfolio Strategy / Investment Alignment",
      "requester": "Investment Manager",
      "request_intent": "Map plan to target investment strategy",
      "business_trigger_context": "Plan draft / approved plan exists",
      "input": "Financial plan; goals; time horizon; risk profile; liquidity needs; mandate constraints",
      "output": "Target portfolio strategy; allocation guidance; investment constraints summary",
      "expectation_to_ai": "Derive a logical target strategy from plan objectives; preserve liquidity / suitability / mandate constraints; highlight where constraints limit ideal plan",
      "human_in_the_loop": "IM",
      "ai_type": "Reasoning / Mapping",
      "priority": "MVP",
      "notes": "AI assists, IM owns decision"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_14": {
    "loop_input": {
      "interaction_id": "assessment_14",
      "journey_phase": "Portfolio Strategy / Investment Alignment",
      "requester": "Investment Manager",
      "request_intent": "Identify portfolio gaps and misalignment",
      "business_trigger_context": "Need to move from current state to target state",
      "input": "Current portfolio holdings; target strategy; risk and liquidity constraints",
      "output": "Gap analysis; misalignment summary; possible rebalancing directions",
      "expectation_to_ai": "Explain what is misaligned; quantify/classify drift; distinguish normal drift vs material drift",
      "human_in_the_loop": "IM",
      "ai_type": "Gap analysis / Drift detection",
      "priority": "MVP",
      "notes": "Input to portfolio recommendation generation"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_15": {
    "loop_input": {
      "interaction_id": "assessment_15",
      "journey_phase": "Portfolio Strategy / Investment Alignment",
      "requester": "Investment Manager",
      "request_intent": "Draft portfolio change recommendation",
      "business_trigger_context": "Gap between current and target portfolio",
      "input": "Current holdings; target allocation; constraints; suitability rules; liquidity needs",
      "output": "Draft recommendation; execution implications; potential issues / exceptions",
      "expectation_to_ai": "Generate recommendation consistent with plan and mandate; flag suitability or compliance issues; distinguish items requiring client approval vs internal review",
      "human_in_the_loop": "IM / WM",
      "ai_type": "Drafting / Recommendation",
      "priority": "MVP",
      "notes": "Must not assume direct trade execution"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_16": {
    "loop_input": {
      "interaction_id": "assessment_16",
      "journey_phase": "Collaboration / Client Delivery",
      "requester": "RM / WM / IM",
      "request_intent": "Summarize internal discussion and unresolved issues",
      "business_trigger_context": "Internal review across RM, WM, IM, Legal, Compliance",
      "input": "Comments; task updates; approvals; case history",
      "output": "Summary of discussion; unresolved issues; next action owner",
      "expectation_to_ai": "Condense long collaboration into actionable summary; identify blockers and dependencies; avoid losing dissent / alternative view",
      "human_in_the_loop": "Requester reviews",
      "ai_type": "Summarization / Collaboration support",
      "priority": "MVP",
      "notes": "Good candidate for task summary"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_17": {
    "loop_input": {
      "interaction_id": "assessment_17",
      "journey_phase": "Collaboration / Client Delivery",
      "requester": "System / RM / WM",
      "request_intent": "Route work to the right specialist / owner",
      "business_trigger_context": "Planning issue, specialist trigger, compliance issue, or client request",
      "input": "Case type; current state; identified issue; role matrix; policy / routing rules",
      "output": "Assigned role(s); recommended workflow path; urgency / SLA",
      "expectation_to_ai": "Determine who should act next; support multi-party routing when needed; avoid sending to the wrong function",
      "human_in_the_loop": "Automatic or reviewed depending on policy",
      "ai_type": "Routing / Orchestration",
      "priority": "MVP",
      "notes": "Core orchestration behavior"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_18": {
    "loop_input": {
      "interaction_id": "assessment_18",
      "journey_phase": "Collaboration / Client Delivery",
      "requester": "RM",
      "request_intent": "Prepare advice for client delivery",
      "business_trigger_context": "Internal recommendation approved",
      "input": "Approved recommendation; client profile; communication preference; internal rationale",
      "output": "Client-facing summary; notification text; supporting explanation",
      "expectation_to_ai": "Simplify complex advice without changing meaning; tailor language to the client; preserve consistency with approved recommendation",
      "human_in_the_loop": "RM",
      "ai_type": "Drafting / Personalization",
      "priority": "MVP",
      "notes": "Critical for client trust"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_19": {
    "loop_input": {
      "interaction_id": "assessment_19",
      "journey_phase": "Collaboration / Client Delivery",
      "requester": "Client",
      "request_intent": "Ask question about recommendation / report / execution result / plan",
      "business_trigger_context": "Client in mobile app",
      "input": "Client question; current screen context; client data; approved recommendation / report",
      "output": "Direct answer; explanation; suggested next actions; escalation to RM when needed",
      "expectation_to_ai": "Answer in plain language; stay grounded in approved data/recommendation; know when to escalate to a human",
      "human_in_the_loop": "Escalate if unclear / sensitive",
      "ai_type": "Conversational assist / Explanation",
      "priority": "MVP",
      "notes": "Requires strong context resolver"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_20": {
    "loop_input": {
      "interaction_id": "assessment_20",
      "journey_phase": "Collaboration / Client Delivery",
      "requester": "System / RM",
      "request_intent": "Interpret client rejection / request change",
      "business_trigger_context": "Client rejects or requests modification",
      "input": "Client decision; client comments; original recommendation",
      "output": "Classification of client concern; follow-up tasks; suggested rework path",
      "expectation_to_ai": "Classify whether issue is risk concern, liquidity concern, misunderstanding, timing concern, or legal/family concern; route to correct internal owner",
      "human_in_the_loop": "RM / WM / IM",
      "ai_type": "Classification / Routing",
      "priority": "MVP",
      "notes": "Useful for workflow automation"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_21": {
    "loop_input": {
      "interaction_id": "assessment_21",
      "journey_phase": "Execution Handoff / Result Update",
      "requester": "IM / Operations",
      "request_intent": "Validate execution handoff readiness",
      "business_trigger_context": "Client approved recommendation",
      "input": "Approved advice; client consent; mandate; execution details; required operational fields",
      "output": "Readiness status; missing items; blockers / exception flags",
      "expectation_to_ai": "Ensure completeness before handoff; request missing operational data; detect remaining compliance / consent issues",
      "human_in_the_loop": "Operations / IM / Compliance if required",
      "ai_type": "Validation / Readiness check",
      "priority": "MVP",
      "notes": "Platform does not execute directly"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_22": {
    "loop_input": {
      "interaction_id": "assessment_22",
      "journey_phase": "Execution Handoff / Result Update",
      "requester": "IM / Operations",
      "request_intent": "Prepare instruction package for external party",
      "business_trigger_context": "Handoff approved",
      "input": "Approved recommendation; validated operational fields; execution metadata",
      "output": "Structured execution request package; handoff summary; traceability reference",
      "expectation_to_ai": "Generate structured, complete handoff package; preserve exact approved intent; do not change business meaning",
      "human_in_the_loop": "Operations / IM",
      "ai_type": "Drafting / Structuring",
      "priority": "MVP",
      "notes": "AI drafts, system transmits"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_23": {
    "loop_input": {
      "interaction_id": "assessment_23",
      "journey_phase": "Execution Handoff / Result Update",
      "requester": "Operations / System",
      "request_intent": "Interpret result returned by external party",
      "business_trigger_context": "External party sends status / confirmation / file / API update",
      "input": "Execution update; instruction reference; status model",
      "output": "Normalized status; parsed result; detected exceptions",
      "expectation_to_ai": "Classify external update into internal lifecycle status; detect partial / failed / delayed / mismatched execution; avoid incorrect mapping",
      "human_in_the_loop": "Operations reviews if exception",
      "ai_type": "Parsing / Classification / Normalization",
      "priority": "MVP",
      "notes": "Can be partly rules-based + AI-assisted"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_24": {
    "loop_input": {
      "interaction_id": "assessment_24",
      "journey_phase": "Execution Handoff / Result Update",
      "requester": "Operations / IM",
      "request_intent": "Compare expected vs actual execution outcome",
      "business_trigger_context": "External result received",
      "input": "Original instruction; actual confirmation; prices / quantities / status",
      "output": "Reconciliation result; discrepancy summary; recommended next action",
      "expectation_to_ai": "Detect all meaningful differences; explain business impact; route exception if needed",
      "human_in_the_loop": "Operations / IM",
      "ai_type": "Reconciliation / Exception analysis",
      "priority": "MVP",
      "notes": "Essential for post-execution truth update"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_25": {
    "loop_input": {
      "interaction_id": "assessment_25",
      "journey_phase": "Execution Handoff / Result Update",
      "requester": "RM / Operations",
      "request_intent": "Draft update to client about execution outcome",
      "business_trigger_context": "Partial execution / failure / cancellation",
      "input": "Reconciliation result; client communication profile; internal decision on next step",
      "output": "Client-facing update; explanation of impact; next-step message",
      "expectation_to_ai": "Explain clearly without causing unnecessary confusion; accurately reflect actual state; separate “what happened” from “what we recommend next”",
      "human_in_the_loop": "RM",
      "ai_type": "Drafting / Client communication",
      "priority": "MVP",
      "notes": "Important trust-preserving interaction"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_26": {
    "loop_input": {
      "interaction_id": "assessment_26",
      "journey_phase": "Monitoring / Periodic Review",
      "requester": "System / WM",
      "request_intent": "Detect deviation between approved plan and actual wealth trajectory",
      "business_trigger_context": "Ongoing monitoring",
      "input": "Current wealth state; approved plan; market conditions; cash flow updates",
      "output": "Drift alert; impact summary; recommended next action",
      "expectation_to_ai": "Detect material drift early; distinguish noise vs actionable issue; identify why drift occurred",
      "human_in_the_loop": "WM reviews",
      "ai_type": "Monitoring / Drift detection",
      "priority": "MVP",
      "notes": "Core AI monitoring capability"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_27": {
    "loop_input": {
      "interaction_id": "assessment_27",
      "journey_phase": "Monitoring / Periodic Review",
      "requester": "System / IM",
      "request_intent": "Monitor investment drift / concentration / liquidity / risk signals",
      "business_trigger_context": "Ongoing monitoring",
      "input": "Live portfolio state; target allocation; market data; suitability / mandate rules",
      "output": "Portfolio alerts; drift explanation; proposed review action",
      "expectation_to_ai": "Identify material investment issues; distinguish advisory vs urgent issue; support prioritization",
      "human_in_the_loop": "IM",
      "ai_type": "Monitoring / Risk detection",
      "priority": "MVP",
      "notes": "Feeds dashboard and action queue"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_28": {
    "loop_input": {
      "interaction_id": "assessment_28",
      "journey_phase": "Monitoring / Periodic Review",
      "requester": "RM / System",
      "request_intent": "Identify which clients need proactive contact",
      "business_trigger_context": "Daily RM workflow",
      "input": "Alerts; client activity; pending approvals; risk / drift signals",
      "output": "Prioritized outreach list; reason for prioritization; suggested talking points",
      "expectation_to_ai": "Rank outreach opportunities intelligently; detect high-touch cases; reduce missed proactive servicing",
      "human_in_the_loop": "RM",
      "ai_type": "Prioritization / Next-best-action",
      "priority": "MVP",
      "notes": "Strong productivity interaction"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_29": {
    "loop_input": {
      "interaction_id": "assessment_29",
      "journey_phase": "Monitoring / Periodic Review",
      "requester": "RM / WM / IM",
      "request_intent": "Prepare periodic review materials",
      "business_trigger_context": "Quarterly / annual review or event-driven review",
      "input": "Historical plan versions; portfolio history; client changes; monitoring alerts",
      "output": "Review pack; meeting brief; suggested agenda / follow-up actions",
      "expectation_to_ai": "Summarize changes since last review; identify major themes; support both internal and client-facing review",
      "human_in_the_loop": "RM / WM / IM",
      "ai_type": "Drafting / Summarization",
      "priority": "MVP",
      "notes": "Reusable document-generation interaction"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_30": {
    "loop_input": {
      "interaction_id": "assessment_30",
      "journey_phase": "Advanced Services / Legal / Tax / Estate",
      "requester": "System / RM / WM / Legal",
      "request_intent": "Detect advanced-service trigger",
      "business_trigger_context": "Ongoing monitoring or discovery/planning",
      "input": "Asset levels; household structure; inheritance / guardian / trustee data; jurisdiction/residency indicators; client updates",
      "output": "Trigger alert; specialist referral recommendation; specific information / document request",
      "expectation_to_ai": "Detect complex cases early; identify when standard wealth planning is not enough; ask for precise additional information / documents",
      "human_in_the_loop": "RM / Legal / Tax",
      "ai_type": "Trigger detection / Routing",
      "priority": "Phase 2",
      "notes": "Important for HNW / family-office cases"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_31": {
    "loop_input": {
      "interaction_id": "assessment_31",
      "journey_phase": "Advanced Services / Legal / Tax / Estate",
      "requester": "Legal / Tax Advisor / WM",
      "request_intent": "Draft structured options and trade-offs",
      "business_trigger_context": "Estate / trust / tax / inheritance case opened",
      "input": "Client structure; legal/tax case facts; prior decisions; planning objectives",
      "output": "Option set; implications summary; required follow-up questions / documents",
      "expectation_to_ai": "Structure complex issues clearly; identify what is still unknown; support specialist decision-making, not replace it",
      "human_in_the_loop": "Legal / Tax / WM",
      "ai_type": "Drafting / Specialist assist",
      "priority": "Phase 2",
      "notes": "Must be tightly governed"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_32": {
    "loop_input": {
      "interaction_id": "assessment_32",
      "journey_phase": "Governance / Compliance / Explainability",
      "requester": "RM / WM / IM / Compliance / Client",
      "request_intent": "Explain recommendation / decision",
      "business_trigger_context": "Need to justify AI-supported output",
      "input": "Recommendation; supporting data; rules applied; rationale",
      "output": "Explanation in role-appropriate language; linked factors; uncertainty / assumptions",
      "expectation_to_ai": "Provide traceable explanation; adapt language by audience (client, RM, specialist, compliance reviewer)",
      "human_in_the_loop": "Depends on usage",
      "ai_type": "Explanation / Explainability",
      "priority": "MVP",
      "notes": "Core explainability service"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_33": {
    "loop_input": {
      "interaction_id": "assessment_33",
      "journey_phase": "Governance / Compliance / Explainability",
      "requester": "Compliance / Risk Officer",
      "request_intent": "Summarize override request and supporting context",
      "business_trigger_context": "Policy breach / override / suitability exception",
      "input": "Exception case; policy rules; recommendation; supporting approval history",
      "output": "Exception summary; impacted rules; reasoned decision-support note",
      "expectation_to_ai": "Clearly identify which rule is affected; summarize facts for reviewer; not self-approve",
      "human_in_the_loop": "Compliance only",
      "ai_type": "Summarization / Governance support",
      "priority": "MVP",
      "notes": "Strict control required"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "assessment_34": {
    "loop_input": {
      "interaction_id": "assessment_34",
      "journey_phase": "Governance / Compliance / Explainability",
      "requester": "System",
      "request_intent": "Determine whether AI should stop and escalate",
      "business_trigger_context": "Any AI interaction",
      "input": "User request; available context; confidence level; rule coverage",
      "output": "Low-confidence flag; escalation reason; request for more data / human review",
      "expectation_to_ai": "Know when not to answer confidently; avoid hallucination; trigger fallback behavior",
      "human_in_the_loop": "Required when flagged",
      "ai_type": "Safety / Confidence management",
      "priority": "MVP",
      "notes": "Critical for production safety"
    },
    "system_prompt": "# Smart Wealth AI — interaction {{interaction_id}}\n\nOperate as **{{ai_type}}** within journey phase: **{{journey_phase}}**.\n\n## Requester (audience / channel owner)\n\n{{requester}}\n\n## Request (intent)\n\n{{request_intent}}\n\n## Business trigger / context\n\n{{business_trigger_context}}\n\n## Input contract (types of facts; concrete values are supplied in the user turn under Variables)\n\n{{input_contract}}\n\n## Output contract (deliverables and shape)\n\n{{output_contract}}\n\n## Expectation to AI (primary task)\n\n{{expectation_to_ai}}\n\n## Human-in-the-loop\n\n{{human_in_the_loop}}\n\n## Priority & notes\n\n- **Priority:** {{priority}}\n- **Notes:** {{notes}}\n\n---\n\n**Rules:** Ground answers in the **Variables** JSON in the user message. Do not invent facts outside approved or supplied data. Follow the output contract and expectation above. If information is insufficient, list gaps and assumptions explicitly. Always reply in the same language as the user's message: Vietnamese input → Vietnamese output; English input → English output."
  },
  "client_profile_context": {
    "loop_input": {
      "interaction_id": "client_profile_context",
      "journey_phase": "Onboarding",
      "requester": "RM / System",
      "request_intent": "Load client identity, household, and case-scoped document links from PostgreSQL for onboarding",
      "business_trigger_context": "Case chat or orchestration variables include case_id or client_id",
      "input": "case_id (UUID) and/or client_id (UUID) in orchestration variables",
      "output": "profile_snapshot.identity_demographics, household, documents (case_document → document when case_id is present); tool uses read-only SQL",
      "expectation_to_ai": "No inference beyond DB; missing tables or rows surface in profile_snapshot.error",
      "human_in_the_loop": "No",
      "ai_type": "Data retrieval (SearchAgent + client_profile_sql_tool)",
      "priority": "MVP",
      "notes": "doc_kind on case_document: IDENTITY_DOCUMENT, PROOF_OF_ADDRESS, TRUST_DEED, BENEFICIARY_SUPPORT, GUARDIAN_SUPPORT; pass case_id to resolve files for that case"
    },
    "system_prompt": "# client_profile_context\n\nOutput is JSON from SearchAgent. Primary payload: ``profile_snapshot`` (from ``client_profile_sql_tool``). Use for downstream completeness or RM chat; do not invent fields not present in the snapshot."
  }
}
"""

INTERACTION_CATALOG_SEED: dict[str, Any] = json.loads(_INTERACTION_CATALOG_SEED_RAW)
