#!/usr/bin/env python3
"""Merge assessment_07 … assessment_34 into ``app/domain/smartwealth/catalog_seed.py`` (loop_input + system_prompt)."""

from __future__ import annotations

import json
import sys
from copy import deepcopy
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from app.prompts import load_prompt  # noqa: E402

_CATALOG_SEED_PY = _ROOT / "app" / "domain" / "smartwealth" / "catalog_seed.py"


def write_catalog_seed_py(dest: Path, manifest: dict[str, Any], catalog: dict[str, Any]) -> None:
    raw_json = json.dumps(catalog, ensure_ascii=False, indent=2)
    if '"""' in raw_json:
        raise SystemExit(
            'Catalog JSON contains """ — embed manually or adjust prompts before regenerating.'
        )
    man_literal = json.dumps(manifest, ensure_ascii=False, indent=4)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        f'''"""Embedded bootstrap data for ``case_phase`` / ``ai_interaction`` DB seed and pytest snapshot mode.

Production runtime SSOT is PostgreSQL. Regenerated by ``scripts/generate_interaction_ai07_ai34.py`` when refreshing assessment_07…assessment_34 templates.
"""

from __future__ import annotations

import json
from typing import Any

CASE_PHASE_ASSESSMENT_MANIFEST: dict[str, Any] = {man_literal}

_INTERACTION_CATALOG_SEED_RAW = r"""
{raw_json}
"""

INTERACTION_CATALOG_SEED: dict[str, Any] = json.loads(_INTERACTION_CATALOG_SEED_RAW)
''',
        encoding="utf-8",
    )

# (interaction_id, journey_phase, requester, request_intent, business_trigger_context, input, output, expectation_to_ai, human_in_the_loop, ai_type, priority, notes)
ROWS: list[tuple[str, ...]] = [
    (
        "assessment_07",
        "Discovery / Data Collection",
        "System / WM / IM",
        "Normalize and interpret client assets / liabilities / holdings",
        "Client entered or linked financial data",
        "Account data; manually entered holdings; asset/liability categories; cash-flow data",
        "Normalized financial structure; categorized assets/liabilities; suspicious / unclear items",
        "Classify financial data correctly; identify ambiguity or inconsistency; detect unusual assets requiring specialist handling",
        "WM / RM / Operations if necessary",
        "Normalization / Classification",
        "MVP",
        "AI should not silently guess unclear assets",
    ),
    (
        "assessment_08",
        "Discovery / Data Collection",
        "Wealth Manager",
        "Detect conflicting goals or constraints",
        "During discovery or plan drafting",
        "Goals; target dates; target amounts; risk tolerance; liquidity requirements; asset base",
        "Identified goal conflicts; trade-off summary; suggested clarification questions",
        "Detect infeasible or conflicting goals; explain conflict in practical terms; suggest which assumptions require confirmation",
        "WM",
        "Reasoning / Conflict detection",
        "MVP",
        "Supports scenario setup",
    ),
    (
        "assessment_09",
        "Plan Creation / Wealth Plan Drafting",
        "Wealth Manager",
        "Build draft wealth plan",
        "Sufficient discovery data available",
        "Client data; goals; assets/liabilities; cash flow; constraints; risk profile; related-party / special-case data",
        "Draft wealth plan; request for more information if needed; assumptions used; key planning rationale",
        "Validate whether information is sufficient; request more information if not enough; produce comprehensive and customized plan draft; detect special situations; ask for specific documents/facts depending on the client situation; avoid generic template planning",
        "WM must review",
        "Reasoning / Drafting / Gap analysis",
        "MVP",
        "Key planning interaction for developers",
    ),
    (
        "assessment_10",
        "Plan Creation / Wealth Plan Drafting",
        "Wealth Manager",
        "Run scenario analysis and compare options",
        "Draft plan available, options needed",
        "Draft plan; assumptions; scenario parameters; client goals and constraints",
        "Scenario comparison; trade-off summary; recommended option",
        "Compare scenarios in goal-oriented form; explain advantages/disadvantages; identify scenarios requiring client confirmation",
        "WM",
        "Scenario analysis / Comparison",
        "MVP",
        "Output should be structured for screen display",
    ),
    (
        "assessment_11",
        "Plan Creation / Wealth Plan Drafting",
        "Wealth Manager / System",
        "Detect need for specialist involvement during planning",
        "During plan drafting",
        "Draft plan; client structure; assets; goals; cross-border / trust / inheritance data",
        "Specialist referral recommendation; reason for referral; suggested tasks/questions",
        "Identify when general planning is not sufficient; trigger Legal / Tax / Compliance appropriately; explain the reason clearly",
        "WM / RM",
        "Routing / Risk flagging",
        "MVP",
        "Feeds routing engine",
    ),
    (
        "assessment_12",
        "Plan Creation / Wealth Plan Drafting",
        "Wealth Manager / RM",
        "Draft plan rationale and client-facing explanation",
        "Draft plan ready for internal review or client delivery",
        "Plan draft; scenario selection; rationale; client profile / communication style",
        "Internal rationale; client-facing explanation; meeting talking points",
        "Produce both professional internal explanation and plain-language client explanation; preserve consistency with approved assumptions",
        "WM / RM",
        "Drafting / Explanation",
        "MVP",
        "Must not introduce new facts not in SSOT",
    ),
    (
        "assessment_13",
        "Portfolio Strategy / Investment Alignment",
        "Investment Manager",
        "Map plan to target investment strategy",
        "Plan draft / approved plan exists",
        "Financial plan; goals; time horizon; risk profile; liquidity needs; mandate constraints",
        "Target portfolio strategy; allocation guidance; investment constraints summary",
        "Derive a logical target strategy from plan objectives; preserve liquidity / suitability / mandate constraints; highlight where constraints limit ideal plan",
        "IM",
        "Reasoning / Mapping",
        "MVP",
        "AI assists, IM owns decision",
    ),
    (
        "assessment_14",
        "Portfolio Strategy / Investment Alignment",
        "Investment Manager",
        "Identify portfolio gaps and misalignment",
        "Need to move from current state to target state",
        "Current portfolio holdings; target strategy; risk and liquidity constraints",
        "Gap analysis; misalignment summary; possible rebalancing directions",
        "Explain what is misaligned; quantify/classify drift; distinguish normal drift vs material drift",
        "IM",
        "Gap analysis / Drift detection",
        "MVP",
        "Input to portfolio recommendation generation",
    ),
    (
        "assessment_15",
        "Portfolio Strategy / Investment Alignment",
        "Investment Manager",
        "Draft portfolio change recommendation",
        "Gap between current and target portfolio",
        "Current holdings; target allocation; constraints; suitability rules; liquidity needs",
        "Draft recommendation; execution implications; potential issues / exceptions",
        "Generate recommendation consistent with plan and mandate; flag suitability or compliance issues; distinguish items requiring client approval vs internal review",
        "IM / WM",
        "Drafting / Recommendation",
        "MVP",
        "Must not assume direct trade execution",
    ),
    (
        "assessment_16",
        "Collaboration / Client Delivery",
        "RM / WM / IM",
        "Summarize internal discussion and unresolved issues",
        "Internal review across RM, WM, IM, Legal, Compliance",
        "Comments; task updates; approvals; case history",
        "Summary of discussion; unresolved issues; next action owner",
        "Condense long collaboration into actionable summary; identify blockers and dependencies; avoid losing dissent / alternative view",
        "Requester reviews",
        "Summarization / Collaboration support",
        "MVP",
        "Good candidate for task summary",
    ),
    (
        "assessment_17",
        "Collaboration / Client Delivery",
        "System / RM / WM",
        "Route work to the right specialist / owner",
        "Planning issue, specialist trigger, compliance issue, or client request",
        "Case type; current state; identified issue; role matrix; policy / routing rules",
        "Assigned role(s); recommended workflow path; urgency / SLA",
        "Determine who should act next; support multi-party routing when needed; avoid sending to the wrong function",
        "Automatic or reviewed depending on policy",
        "Routing / Orchestration",
        "MVP",
        "Core orchestration behavior",
    ),
    (
        "assessment_18",
        "Collaboration / Client Delivery",
        "RM",
        "Prepare advice for client delivery",
        "Internal recommendation approved",
        "Approved recommendation; client profile; communication preference; internal rationale",
        "Client-facing summary; notification text; supporting explanation",
        "Simplify complex advice without changing meaning; tailor language to the client; preserve consistency with approved recommendation",
        "RM",
        "Drafting / Personalization",
        "MVP",
        "Critical for client trust",
    ),
    (
        "assessment_19",
        "Collaboration / Client Delivery",
        "Client",
        "Ask question about recommendation / report / execution result / plan",
        "Client in mobile app",
        "Client question; current screen context; client data; approved recommendation / report",
        "Direct answer; explanation; suggested next actions; escalation to RM when needed",
        "Answer in plain language; stay grounded in approved data/recommendation; know when to escalate to a human",
        "Escalate if unclear / sensitive",
        "Conversational assist / Explanation",
        "MVP",
        "Requires strong context resolver",
    ),
    (
        "assessment_20",
        "Collaboration / Client Delivery",
        "System / RM",
        "Interpret client rejection / request change",
        "Client rejects or requests modification",
        "Client decision; client comments; original recommendation",
        "Classification of client concern; follow-up tasks; suggested rework path",
        "Classify whether issue is risk concern, liquidity concern, misunderstanding, timing concern, or legal/family concern; route to correct internal owner",
        "RM / WM / IM",
        "Classification / Routing",
        "MVP",
        "Useful for workflow automation",
    ),
    (
        "assessment_21",
        "Execution Handoff / Result Update",
        "IM / Operations",
        "Validate execution handoff readiness",
        "Client approved recommendation",
        "Approved advice; client consent; mandate; execution details; required operational fields",
        "Readiness status; missing items; blockers / exception flags",
        "Ensure completeness before handoff; request missing operational data; detect remaining compliance / consent issues",
        "Operations / IM / Compliance if required",
        "Validation / Readiness check",
        "MVP",
        "Platform does not execute directly",
    ),
    (
        "assessment_22",
        "Execution Handoff / Result Update",
        "IM / Operations",
        "Prepare instruction package for external party",
        "Handoff approved",
        "Approved recommendation; validated operational fields; execution metadata",
        "Structured execution request package; handoff summary; traceability reference",
        "Generate structured, complete handoff package; preserve exact approved intent; do not change business meaning",
        "Operations / IM",
        "Drafting / Structuring",
        "MVP",
        "AI drafts, system transmits",
    ),
    (
        "assessment_23",
        "Execution Handoff / Result Update",
        "Operations / System",
        "Interpret result returned by external party",
        "External party sends status / confirmation / file / API update",
        "Execution update; instruction reference; status model",
        "Normalized status; parsed result; detected exceptions",
        "Classify external update into internal lifecycle status; detect partial / failed / delayed / mismatched execution; avoid incorrect mapping",
        "Operations reviews if exception",
        "Parsing / Classification / Normalization",
        "MVP",
        "Can be partly rules-based + AI-assisted",
    ),
    (
        "assessment_24",
        "Execution Handoff / Result Update",
        "Operations / IM",
        "Compare expected vs actual execution outcome",
        "External result received",
        "Original instruction; actual confirmation; prices / quantities / status",
        "Reconciliation result; discrepancy summary; recommended next action",
        "Detect all meaningful differences; explain business impact; route exception if needed",
        "Operations / IM",
        "Reconciliation / Exception analysis",
        "MVP",
        "Essential for post-execution truth update",
    ),
    (
        "assessment_25",
        "Execution Handoff / Result Update",
        "RM / Operations",
        "Draft update to client about execution outcome",
        "Partial execution / failure / cancellation",
        "Reconciliation result; client communication profile; internal decision on next step",
        "Client-facing update; explanation of impact; next-step message",
        "Explain clearly without causing unnecessary confusion; accurately reflect actual state; separate “what happened” from “what we recommend next”",
        "RM",
        "Drafting / Client communication",
        "MVP",
        "Important trust-preserving interaction",
    ),
    (
        "assessment_26",
        "Monitoring / Periodic Review",
        "System / WM",
        "Detect deviation between approved plan and actual wealth trajectory",
        "Ongoing monitoring",
        "Current wealth state; approved plan; market conditions; cash flow updates",
        "Drift alert; impact summary; recommended next action",
        "Detect material drift early; distinguish noise vs actionable issue; identify why drift occurred",
        "WM reviews",
        "Monitoring / Drift detection",
        "MVP",
        "Core AI monitoring capability",
    ),
    (
        "assessment_27",
        "Monitoring / Periodic Review",
        "System / IM",
        "Monitor investment drift / concentration / liquidity / risk signals",
        "Ongoing monitoring",
        "Live portfolio state; target allocation; market data; suitability / mandate rules",
        "Portfolio alerts; drift explanation; proposed review action",
        "Identify material investment issues; distinguish advisory vs urgent issue; support prioritization",
        "IM",
        "Monitoring / Risk detection",
        "MVP",
        "Feeds dashboard and action queue",
    ),
    (
        "assessment_28",
        "Monitoring / Periodic Review",
        "RM / System",
        "Identify which clients need proactive contact",
        "Daily RM workflow",
        "Alerts; client activity; pending approvals; risk / drift signals",
        "Prioritized outreach list; reason for prioritization; suggested talking points",
        "Rank outreach opportunities intelligently; detect high-touch cases; reduce missed proactive servicing",
        "RM",
        "Prioritization / Next-best-action",
        "MVP",
        "Strong productivity interaction",
    ),
    (
        "assessment_29",
        "Monitoring / Periodic Review",
        "RM / WM / IM",
        "Prepare periodic review materials",
        "Quarterly / annual review or event-driven review",
        "Historical plan versions; portfolio history; client changes; monitoring alerts",
        "Review pack; meeting brief; suggested agenda / follow-up actions",
        "Summarize changes since last review; identify major themes; support both internal and client-facing review",
        "RM / WM / IM",
        "Drafting / Summarization",
        "MVP",
        "Reusable document-generation interaction",
    ),
    (
        "assessment_30",
        "Advanced Services / Legal / Tax / Estate",
        "System / RM / WM / Legal",
        "Detect advanced-service trigger",
        "Ongoing monitoring or discovery/planning",
        "Asset levels; household structure; inheritance / guardian / trustee data; jurisdiction/residency indicators; client updates",
        "Trigger alert; specialist referral recommendation; specific information / document request",
        "Detect complex cases early; identify when standard wealth planning is not enough; ask for precise additional information / documents",
        "RM / Legal / Tax",
        "Trigger detection / Routing",
        "Phase 2",
        "Important for HNW / family-office cases",
    ),
    (
        "assessment_31",
        "Advanced Services / Legal / Tax / Estate",
        "Legal / Tax Advisor / WM",
        "Draft structured options and trade-offs",
        "Estate / trust / tax / inheritance case opened",
        "Client structure; legal/tax case facts; prior decisions; planning objectives",
        "Option set; implications summary; required follow-up questions / documents",
        "Structure complex issues clearly; identify what is still unknown; support specialist decision-making, not replace it",
        "Legal / Tax / WM",
        "Drafting / Specialist assist",
        "Phase 2",
        "Must be tightly governed",
    ),
    (
        "assessment_32",
        "Governance / Compliance / Explainability",
        "RM / WM / IM / Compliance / Client",
        "Explain recommendation / decision",
        "Need to justify AI-supported output",
        "Recommendation; supporting data; rules applied; rationale",
        "Explanation in role-appropriate language; linked factors; uncertainty / assumptions",
        "Provide traceable explanation; adapt language by audience (client, RM, specialist, compliance reviewer)",
        "Depends on usage",
        "Explanation / Explainability",
        "MVP",
        "Core explainability service",
    ),
    (
        "assessment_33",
        "Governance / Compliance / Explainability",
        "Compliance / Risk Officer",
        "Summarize override request and supporting context",
        "Policy breach / override / suitability exception",
        "Exception case; policy rules; recommendation; supporting approval history",
        "Exception summary; impacted rules; reasoned decision-support note",
        "Clearly identify which rule is affected; summarize facts for reviewer; not self-approve",
        "Compliance only",
        "Summarization / Governance support",
        "MVP",
        "Strict control required",
    ),
    (
        "assessment_34",
        "Governance / Compliance / Explainability",
        "System",
        "Determine whether AI should stop and escalate",
        "Any AI interaction",
        "User request; available context; confidence level; rule coverage",
        "Low-confidence flag; escalation reason; request for more data / human review",
        "Know when not to answer confidently; avoid hallucination; trigger fallback behavior",
        "Required when flagged",
        "Safety / Confidence management",
        "MVP",
        "Critical for production safety",
    ),
]

PROMPT_TEMPLATE = load_prompt("assessment_template")


def main() -> None:
    from app.domain.smartwealth.catalog_seed import (
        CASE_PHASE_ASSESSMENT_MANIFEST,
        INTERACTION_CATALOG_SEED,
    )

    catalog = deepcopy(INTERACTION_CATALOG_SEED)
    keys = (
        "interaction_id",
        "journey_phase",
        "requester",
        "request_intent",
        "business_trigger_context",
        "input",
        "output",
        "expectation_to_ai",
        "human_in_the_loop",
        "ai_type",
        "priority",
        "notes",
    )
    for row in ROWS:
        obj = dict(zip(keys, row, strict=True))
        iid = obj["interaction_id"]
        catalog[iid] = {"loop_input": dict(obj), "system_prompt": PROMPT_TEMPLATE}
    write_catalog_seed_py(_CATALOG_SEED_PY, CASE_PHASE_ASSESSMENT_MANIFEST, catalog)
    print(f"Merged {len(ROWS)} interactions into {_CATALOG_SEED_PY}")


if __name__ == "__main__":
    main()
